version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "workout-dev"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
region = "ap-northeast-1"
s3_prefix = "workout-dev"
parameter_overrides = "Stage=dev"
confirm_changeset = false
fail_on_empty_changeset = false
