version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "workout-dev"
capabilities = "CAPABILITY_IAM"
region = "ap-northeast-1"
s3_prefix = "workout-dev"
resolve_s3 = false
s3_bucket = "workout-journal-sam-artifacts-986340587505-ap-northeast-1"
parameter_overrides = "Stage=dev"
confirm_changeset = false
fail_on_empty_changeset = false
